"""
Django settings for ISCAGENTProject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charge les variables d'un fichier .env local (HF_TOKEN notamment),
# sans dépendance externe.
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    for _line in _env_file.read_text(encoding='utf-8').splitlines():
        _line = _line.strip()
        if _line and not _line.startswith('#') and '=' in _line:
            _key, _, _value = _line.partition('=')
            os.environ.setdefault(_key.strip(), _value.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Définie dans le fichier .env (DJANGO_SECRET_KEY) ; la valeur de secours
# ci-dessous ne sert qu'au développement local.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-=#!@&du1l6_t(p%!^-=3r!dwq6dhgmjh%ltf@-ta0xhk5#$e_o',
)

# SECURITY WARNING: don't run with debug turned on in production!
# DJANGO_DEBUG=0 dans le .env pour désactiver.
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

# Liste séparée par des virgules, ex : DJANGO_ALLOWED_HOSTS=monsite.fr,www.monsite.fr
ALLOWED_HOSTS = [
    hote.strip()
    for hote in os.environ.get('DJANGO_ALLOWED_HOSTS', 'iscagentbyhady.onrender.com').split(',')
    if hote.strip()
]

# Ex : DJANGO_CSRF_TRUSTED_ORIGINS=https://monsite.fr
CSRF_TRUSTED_ORIGINS = [
    origine.strip()
    for origine in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origine.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'academics',
    'assistant',
]

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'assistant:tableau_de_bord'
LOGOUT_REDIRECT_URL = 'accounts:login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ISCAGENTProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ISCAGENTProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# En production (Render, Heroku, Fly...), définir DATABASE_URL dans
# l'environnement bascule automatiquement sur PostgreSQL.
if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

# Dossier de collecte (collectstatic) servi par whitenoise en production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Configuration de l'agent IA (smolagents + Hugging Face) ---

# Token d'accès Hugging Face : à définir dans un fichier .env à la racine
# du projet (HF_TOKEN=hf_xxx) ou comme variable d'environnement.
HF_TOKEN = os.environ.get('HF_TOKEN', '')

# Modèle principal qui pilote l'agent (raisonnement + choix des tools).
AGENT_MODEL_ID = os.environ.get('AGENT_MODEL_ID', 'Qwen/Qwen2.5-72B-Instruct')

# Modèle secondaire utilisé par les tools de résumé / quiz / fiches.
GENERATION_MODEL_ID = os.environ.get('GENERATION_MODEL_ID', 'Qwen/Qwen2.5-72B-Instruct')

# Nombre maximal d'étapes de raisonnement de l'agent.
AGENT_MAX_STEPS = 6

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
