# Generated by Django 5.2.8 on 2026-06-12 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Nouvelle conversation', max_length=120, verbose_name='titre')),
                ('creee_le', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('mise_a_jour_le', models.DateTimeField(auto_now=True, verbose_name='mise à jour le')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'conversation',
                'ordering': ['-mise_a_jour_le'],
            },
        ),
        migrations.CreateModel(
            name='FicheRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu (markdown)')),
                ('creee_le', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to='academics.cours', verbose_name='cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
            ],
            options={
                'verbose_name': 'fiche de révision',
                'verbose_name_plural': 'fiches de révision',
                'ordering': ['-creee_le'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(choices=[('UTILISATEUR', 'Utilisateur'), ('AGENT', 'Agent')], max_length=12, verbose_name='auteur')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('tools_utilises', models.CharField(blank=True, help_text="Noms des tools appelés par l'agent pour produire cette réponse.", max_length=250, verbose_name='tools utilisés')),
                ('envoye_le', models.DateTimeField(auto_now_add=True, verbose_name='envoyé le')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'message',
                'ordering': ['envoye_le'],
            },
        ),
        migrations.CreateModel(
            name='SimulationExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(verbose_name='questions')),
                ('reponses', models.JSONField(blank=True, null=True, verbose_name='réponses')),
                ('note_sur_20', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='note sur 20')),
                ('commencee_le', models.DateTimeField(auto_now_add=True, verbose_name='commencée le')),
                ('terminee_le', models.DateTimeField(blank=True, null=True, verbose_name='terminée le')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='academics.cours', verbose_name='cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
            ],
            options={
                'verbose_name': "simulation d'examen",
                'verbose_name_plural': "simulations d'examen",
                'ordering': ['-commencee_le'],
            },
        ),
    ]
