# Generated by Django 5.2.8 on 2026-06-12 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='code')),
                ('intitule', models.CharField(max_length=150, verbose_name='intitulé')),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2, verbose_name='niveau')),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], default='S1', max_length=2, verbose_name='semestre')),
                ('enseignant', models.CharField(max_length=100, verbose_name='enseignant')),
                ('credits', models.PositiveSmallIntegerField(default=4, verbose_name='crédits ECTS')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'cours',
                'verbose_name_plural': 'cours',
                'ordering': ['niveau', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CreneauEDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')], verbose_name='jour')),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('salle', models.CharField(max_length=30, verbose_name='salle')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='academics.cours', verbose_name='cours')),
            ],
            options={
                'verbose_name': "créneau d'emploi du temps",
                'verbose_name_plural': "créneaux d'emploi du temps",
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('fichier', models.FileField(upload_to='documents_cours/', verbose_name='fichier PDF')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True, verbose_name='ajouté le')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academics.cours', verbose_name='cours')),
            ],
            options={
                'verbose_name': 'document de cours',
                'verbose_name_plural': 'documents de cours',
                'ordering': ['-ajoute_le'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(choices=[('PARTIEL', 'Partiel'), ('FINAL', 'Examen final'), ('RATTRAPAGE', 'Rattrapage')], default='PARTIEL', max_length=12, verbose_name="type d'épreuve")),
                ('date', models.DateTimeField(verbose_name='date et heure')),
                ('duree_minutes', models.PositiveSmallIntegerField(default=120, verbose_name='durée (minutes)')),
                ('salle', models.CharField(max_length=30, verbose_name='salle')),
                ('consignes', models.TextField(blank=True, verbose_name='consignes')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='academics.cours', verbose_name='cours')),
            ],
            options={
                'verbose_name': 'examen',
                'verbose_name_plural': 'examens',
                'ordering': ['date'],
            },
        ),
    ]
